# -*- coding: utf-8 -*-
"""face_detection_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8WR4ju15NgyewOga1BgzAAV-1BN6J3v
"""

import cv2
from google.colab.patches import cv2_imshow

!unzip /content/ML.zip

imagePath = '/content/IMG_20181127_125429.jpg'
cascPath = '/content/haarcascade_frontalface_default.xml'

faceCascade = cv2.CascadeClassifier(cascPath)

image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)

faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30)
    #flags = cv2.CV_HAAR_SCALE_IMAGE
)

print("Found {0} faces!".format(len(faces)))

for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2_imshow(image)
cv2.waitKey(0)

